#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# CanSen documentation build configuration file, created by
# sphinx-quickstart on Tue Jan 21 07:29:58 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import datetime
import pkg_resources

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.insert(0, os.path.abspath('..'))

# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.katex',
]

intersphinx_mapping = {
    'python': ('https://docs.python.org/3.7', None),
    'cantera': ('https://cantera.org/documentation/docs-2.4/sphinx/html/', None)
}

katex_version = '0.10.0-rc1'

add_function_parentheses = False
autodoc_default_flags = ['members', 'show-inheritance']
autodoc_member_order = 'bysource'
autoclass_content = 'both'

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = 'CanSen'
this_year = datetime.date.today().year
copyright = '{}, {}'.format(this_year, 'Bryan W. Weber')

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

try:
    release = pkg_resources.get_distribution(project).version
except pkg_resources.DistributionNotFound:
    release = 'unknown'
# The short X.Y version.
version = '.'.join(release.split('.')[:1])

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', 'keywords.py', '_piston', '.DS_Store']

# The reST default role (used for this markup: `text`) to use for all
# documents.
default_role = None

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
html_theme_options = {
    'github_user': 'bryanwweber',
    'github_repo': 'CanSen',
    'github_banner': True,
    'github_button': True,
    'show_powered_by': True,
}

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = 'CanSen'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Output file base name for HTML help builder.
htmlhelp_basename = 'CanSendoc'


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
  ('index', 'CanSen.tex', 'CanSen Documentation',
   'Bryan W. Weber', 'manual'),
]

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    ('index', 'cansen', 'CanSen Documentation',
     ['Bryan W. Weber'], 1)
]

# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
  ('index', 'CanSen', 'CanSen Documentation',
   'Bryan W. Weber', 'CanSen', 'One line description of project.',
   'Miscellaneous'),
]
