{% set data = load_setup_py_data() %}

package:
  name: cansen
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - cansen = cansen.__main__:main
  noarch: python

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python >=3.4
    - numpy >=1.8.1,<2.0
    - pytables >=3.1.1,<4.0
    - cantera >=2.2,<3.0

test:
  imports:
    - cansen

about:
  home: https://github.com/bryanwweber/CanSen
  license: MIT
  license_file: LICENSE.txt
